/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicao.gui;

import eleicao.core.Eleitor;
import eleicao.utils.Recursos;
import eleicao.utils.SecurityUtils;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author menuInicial
 */
public class autenticacao extends javax.swing.JDialog {
    menuInicial menu;
    Eleitor e;
    ImageIcon icon;
    DefaultListModel dList;
    int tamanho;
    int index;
    int indiceElect;
    File f;

    /**
     * Creates new form Autenticacao
     * @param parent
     * @param model
     */
    public autenticacao(menuInicial parent, boolean model) {
        super(parent, model);
        this.menu = parent;
        initComponents();
        ImageIcon icon = new ImageIcon("../Eleicao_Blockchain_Teste/img/Votacao.png");
        Image imagem = icon.getImage().getScaledInstance(imgElection.getWidth(), imgElection.getHeight(), Image.SCALE_SMOOTH);
        imgElection.setIcon(icon);
        if (menu.eleitores != null) {
            dList = Recursos.listaEleitores(menu.eleitores);
            tamanho = dList.getSize();
            listEleitores.setModel(dList);
            index = 0;
            listEleitores.setSelectedIndex(index);
        }
        panelPass.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumCC = new javax.swing.JTextField();
        imgElection = new javax.swing.JLabel();
        panelPass = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtElector = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEleitores = new javax.swing.JList<>();
        panelEleitor = new javax.swing.JPanel();
        imgEleitor = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        txtEleitor = new javax.swing.JLabel();
        btnSair2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autenticação");

        jLabel1.setText("Número de CC");

        txtNumCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumCCKeyPressed(evt);
            }
        });

        imgElection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");

        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasstxtPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelPassLayout = new javax.swing.GroupLayout(panelPass);
        panelPass.setLayout(panelPassLayout);
        panelPassLayout.setHorizontalGroup(
            panelPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPassLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPassLayout.setVerticalGroup(
            panelPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPassLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txtElector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtElector, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imgElection, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(txtElector, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgElection, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Autenticação", jPanel1);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Pesquisa.png"))); // NOI18N
        btnPesquisa.setText("Pesquisa");
        btnPesquisa.setHideActionText(true);
        btnPesquisa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        listEleitores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEleitores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEleitoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEleitores);

        javax.swing.GroupLayout imgEleitorLayout = new javax.swing.GroupLayout(imgEleitor);
        imgEleitor.setLayout(imgEleitorLayout);
        imgEleitorLayout.setHorizontalGroup(
            imgEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        imgEleitorLayout.setVerticalGroup(
            imgEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtEleitor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnSair2.setText("Sair");
        btnSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEleitorLayout = new javax.swing.GroupLayout(panelEleitor);
        panelEleitor.setLayout(panelEleitorLayout);
        panelEleitorLayout.setHorizontalGroup(
            panelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEleitorLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imgEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEleitorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair2)
                .addGap(176, 176, 176))
        );
        panelEleitorLayout.setVerticalGroup(
            panelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEleitorLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(btnSair2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelEleitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(imgEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa))
                    .addComponent(panelEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(txtPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Eleitores", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasstxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasstxtPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            try {
                PrivateKey privKey = SecurityUtils.loadPrivateKey("..\\Eleicao_BlockChain_Teste\\eleitores\\" + e.getNome() + "\\key.priv");
                String passWD = new String(SecurityUtils.decrypt(e.getPassword(), privKey), StandardCharsets.UTF_8);
                String getpass = new String(txtPass.getPassword()).trim();
                if(passWD.equals(getpass)){
                    this.dispose();
                    new perfil(this, menu, e, indiceElect, true).setVisible(true);
                } else {
                    JOptionPane.showConfirmDialog(null, "Password incorreta"
                        + "\nIntroduza um número de eleitor válido.", "Eleitor não encontrado", 2);
                }
            } catch (Exception ex) {
                Logger.getLogger(autenticacao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtPasstxtPasswordKeyPressed

    private void txtNumCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCCKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == '\n') {
            int tamanho = menu.eleitores.size() - 1;
            for (int i = 0; i <= tamanho; i++) {
                if (txtNumCC.getText().trim().equals(menu.eleitores.get(i).getCC())) {
                    e = new Eleitor(menu.eleitores.get(i));
                    indiceElect = i;
                    txtElector.setText(menu.eleitores.get(i).toString());
                    icon = new ImageIcon(e.getImagem());
                    Image imagem = icon.getImage().getScaledInstance(imgElection.getWidth(), imgElection.getHeight(), Image.SCALE_SMOOTH);
                    imgElection.setIcon(new ImageIcon(imagem));
                    panelPass.setVisible(true);
                    break;
                }
            }
        }
    }//GEN-LAST:event_txtNumCCKeyPressed

    private void listEleitoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEleitoresValueChanged
        // TODO add your handling code here:
        tamanho = dList.size();
        Eleitor e = (Eleitor) listEleitores.getSelectedValues()[0];
        index = listEleitores.getSelectedIndex();
        menu.eleitores.get(index);
        txtEleitor.setText(menu.eleitores.get(index).toString());
        icon = new ImageIcon(e.getImagem());
        Image imagem = icon.getImage().getScaledInstance(imgLabel.getWidth(), imgLabel.getHeight(), Image.SCALE_SMOOTH);
        imgEleitor.setBackground(Color.white);
        imgLabel.setBackground(Color.white);
        imgLabel.setIcon(new ImageIcon(imagem));

    }//GEN-LAST:event_listEleitoresValueChanged

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <= menu.eleitores.size() - 1; i++) {
            if (txtPesquisa.getText().trim().equals(menu.eleitores.get(i).getCC())) {
                listEleitores.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new menuInicial();
        } catch (Exception ex) {
            Logger.getLogger(autenticacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new menuInicial().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(autenticacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSair2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair2;
    private javax.swing.JLabel imgElection;
    private javax.swing.JPanel imgEleitor;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listEleitores;
    private javax.swing.JPanel panelEleitor;
    private javax.swing.JPanel panelPass;
    private javax.swing.JLabel txtElector;
    private javax.swing.JLabel txtEleitor;
    private javax.swing.JTextField txtNumCC;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
