package eleicao.gui;

import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author menuInicial
 */
public class configEleicaoMenu extends javax.swing.JDialog {

    menuInicial menu;

    /**
     * Creates new form configEleicao
     * @param parent
     * @param model
     */
    public configEleicaoMenu(menuInicial parent, boolean model) {
        super(parent, model);
        this.menu = parent;
        initComponents();
         if (menu.eleicao.getNome() == null){
            txtNome.setEnabled(false);
            txtNome.setVisible(false);
            labelNome.setEnabled(false);
            labelNome.setVisible(false);
        }else{
            txtNome.setText(menu.eleicao.getNome());
            txtNome.setEnabled(true);
            txtNome.setVisible(true);
            labelNome.setEnabled(true);
            labelNome.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEleitores = new javax.swing.JButton();
        btnInfos = new javax.swing.JButton();
        btnCandidatos = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuração Eleição");
        setMinimumSize(new java.awt.Dimension(550, 450));
        setPreferredSize(new java.awt.Dimension(550, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEleitores.setBackground(new java.awt.Color(128, 171, 255));
        btnEleitores.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnEleitores.setText("Eleitores");
        btnEleitores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleitoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnEleitores, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 200, 150));

        btnInfos.setBackground(new java.awt.Color(128, 171, 255));
        btnInfos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnInfos.setText("Informações");
        btnInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 200, 150));

        btnCandidatos.setBackground(new java.awt.Color(128, 171, 255));
        btnCandidatos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnCandidatos.setText("Candidatos");
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 200, 150));

        labelNome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        labelNome.setText("Nome:");
        getContentPane().add(labelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 50, 25));

        txtNome.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 350, 25));

        btnSair.setBackground(new java.awt.Color(128, 171, 255));
        btnSair.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfosActionPerformed
        this.dispose();
        new menuInfos(this, menu, true).setVisible(true);
    }//GEN-LAST:event_btnInfosActionPerformed

    private void btnEleitoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleitoresActionPerformed
        this.dispose();
        new menuEleitor(this, menu, true).setVisible(true);
    }//GEN-LAST:event_btnEleitoresActionPerformed

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
        this.dispose();
        new menuCandidato(this, menu, true).setVisible(true);
    }//GEN-LAST:event_btnCandidatosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            new menuInicial();
        } catch (Exception ex) {
            Logger.getLogger(configEleicaoMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnEleitores;
    private javax.swing.JButton btnInfos;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel txtNome;
    // End of variables declaration//GEN-END:variables
}
