/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicao.gui;

import eleicao.blockchain.Block;
import eleicao.blockchain.BlockChain;
import eleicao.blockchain.MerkleTreeString;
import eleicao.blockchain.Miner;
import eleicao.core.Candidato;
import eleicao.core.Eleicao;
import eleicao.core.Eleitor;
import eleicao.core.Voto;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author joaob
 */
public class menuInicial extends javax.swing.JFrame {

    ArrayList<Eleitor> eleitores;
    ArrayList<Candidato> candidatos;
    ArrayList<Voto> votos;
    ArrayList<Eleitor> votantes;
    Eleicao eleicao;
    ArrayList<Integer> resultados;
    BlockChain blockchain;
    Block block;
    MerkleTreeString tree;
    Miner mineiro;

    /**
     * Creates new form Menu
     */
    public menuInicial() throws Exception {
        eleitores = new ArrayList<>();
        candidatos = new ArrayList<>();
        votos = new ArrayList<>();
        votantes = new ArrayList<>();
        resultados = new ArrayList<>();
        eleicao = new Eleicao(eleitores, candidatos, votos, resultados);
        tree = new MerkleTreeString();
        mineiro = new Miner();
        blockchain = new BlockChain();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfigEleicao = new javax.swing.JButton();
        btnVotar = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnConfigurar = new javax.swing.JMenuItem();
        btnVote = new javax.swing.JMenuItem();
        btnResults = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");

        btnConfigEleicao.setBackground(new java.awt.Color(128, 171, 255));
        btnConfigEleicao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfigEleicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Config.png"))); // NOI18N
        btnConfigEleicao.setText("Config. Eleição");
        btnConfigEleicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigEleicaoActionPerformed(evt);
            }
        });

        btnVotar.setBackground(new java.awt.Color(128, 171, 255));
        btnVotar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Vote.png"))); // NOI18N
        btnVotar.setText("Votar         ");
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        btnResultados.setBackground(new java.awt.Color(128, 171, 255));
        btnResultados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Results.png"))); // NOI18N
        btnResultados.setText("Resultados");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        jMenu1.setText("Eleições");
        jMenu1.setInheritsPopupMenu(true);

        btnConfigurar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnConfigurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/ConfigEleicaoRedimensionado.png"))); // NOI18N
        btnConfigurar.setText("Configurar");
        btnConfigurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigurarActionPerformed(evt);
            }
        });
        jMenu1.add(btnConfigurar);

        btnVote.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnVote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/VoteRedimensionado.png"))); // NOI18N
        btnVote.setText("Votar");
        btnVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoteActionPerformed(evt);
            }
        });
        jMenu1.add(btnVote);

        btnResults.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/ResultadosRedimensionado.png"))); // NOI18N
        btnResults.setText("Resultados");
        btnResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultsActionPerformed(evt);
            }
        });
        jMenu1.add(btnResults);
        jMenu1.add(jSeparator1);

        btnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jMenu1.add(btnSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aplicação");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/AcercaDe.png"))); // NOI18N
        jMenuItem1.setText("Acerca de ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfigEleicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVotar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnConfigEleicao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        new autenticacao(this, true).setVisible(true);
    }//GEN-LAST:event_btnVotarActionPerformed

    private void btnConfigEleicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigEleicaoActionPerformed
        // TODO add your handling code here:
        new configEleicaoMenu(this, true).setVisible(true);
    }//GEN-LAST:event_btnConfigEleicaoActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        // TODO add your handling code here:
        new resultados(this, true).setVisible(true);
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultsActionPerformed
        // TODO add your handling code here:
        new resultados(this, true).setVisible(true);
    }//GEN-LAST:event_btnResultsActionPerformed

    private void btnConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigurarActionPerformed
        // TODO add your handling code here:
        new configEleicaoMenu(this, true).setVisible(true);                
    }//GEN-LAST:event_btnConfigurarActionPerformed

    private void btnVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoteActionPerformed
        // TODO add your handling code here:
        new autenticacao(this, true).setVisible(true);
    }//GEN-LAST:event_btnVoteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new acercaDe(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menuInicial().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(menuInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfigEleicao;
    private javax.swing.JMenuItem btnConfigurar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JMenuItem btnResults;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JButton btnVotar;
    private javax.swing.JMenuItem btnVote;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
