/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicao.gui;

import eleicao.blockchain.Block;
import eleicao.blockchain.Hash;
import eleicao.blockchain.MerkleTreeString;
import eleicao.core.Candidato;
import eleicao.core.Eleicao;
import eleicao.core.Eleitor;
import eleicao.utils.Recursos;
import eleicao.core.Voto;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.temporal.ChronoField;
import java.time.temporal.Temporal;
import java.time.temporal.TemporalField;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author joaob
 */
public class menuVotar extends javax.swing.JDialog {

    menuInicial menu;
    Eleitor e;
    Voto v;
    Candidato cand;
    ImageIcon iconEleitor;
    Image imagEleitor;
    ImageIcon iconCandidato;
    Image imagCandidato;
    int tamanhoCands;
    int index;
    File f;
    DefaultListModel dList;
    int indiceElect;
    MerkleTreeString tree;

    /*
     * Creates new form menuVotar
     */
    /**
     *
     * @param parent
     * @param menu
     * @param eleitor
     * @param indiceElect
     * @param model
     */
    public menuVotar(JDialog parent, menuInicial menu, Eleitor eleitor, int indiceElect, boolean model) {
        super(parent, model);
        this.menu = menu;
        this.e = new Eleitor(eleitor);
        this.indiceElect = indiceElect;
        initComponents();
        dList = Recursos.listaCandidatos(menu.candidatos);
        listCandidatos.setModel(dList);
        index = dList.size();
        listCandidatos.setSelectedIndex(index - 1);
        tamanhoCands = menu.candidatos.size() - 1;
        cand = menu.candidatos.get(tamanhoCands);
        txtNome.setText(e.getNome());
        txtNumCC.setText("Número de CC = " + e.getCC());
        txtDataNasc.setText(e.getDatatoString());
        iconEleitor = new ImageIcon(e.getImagem());
        imagEleitor = iconEleitor.getImage().getScaledInstance(imgEleitor.getWidth(), imgEleitor.getHeight(), Image.SCALE_SMOOTH);
        imgEleitor.setIcon(new ImageIcon(imagEleitor));
        iconCandidato = new ImageIcon(menu.candidatos.get(tamanhoCands).getImagem());
        imagCandidato = iconCandidato.getImage().getScaledInstance(imgEleitor.getWidth(), imgEleitor.getHeight(), Image.SCALE_SMOOTH);
        imgCandidato.setIcon(new ImageIcon(imagCandidato));
        labelCandidato.setText(cand.getNome());
    }

    /*public Block criarBloco(Voto v){
        while(menu.tree.getElements().size() < 8){
            menu.tree.getElements().add(v);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumCC = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgEleitor = new javax.swing.JLabel();
        txtNome = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JLabel();
        btnVotar = new javax.swing.JButton();
        panelBotoesVoto = new javax.swing.JPanel();
        panelCandidato = new javax.swing.JPanel();
        imgCandidato = new javax.swing.JLabel();
        labelCandidato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCandidatos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Votação");
        setName("Votação"); // NOI18N

        txtNumCC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgEleitor, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        txtDataNasc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnVotar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/votar.png"))); // NOI18N
        btnVotar.setMinimumSize(new java.awt.Dimension(128, 128));
        btnVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVotarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCandidatoLayout = new javax.swing.GroupLayout(panelCandidato);
        panelCandidato.setLayout(panelCandidatoLayout);
        panelCandidatoLayout.setHorizontalGroup(
            panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCandidato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        panelCandidatoLayout.setVerticalGroup(
            panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCandidato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelBotoesVotoLayout = new javax.swing.GroupLayout(panelBotoesVoto);
        panelBotoesVoto.setLayout(panelBotoesVotoLayout);
        panelBotoesVotoLayout.setHorizontalGroup(
            panelBotoesVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesVotoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBotoesVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBotoesVotoLayout.setVerticalGroup(
            panelBotoesVotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesVotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        listCandidatos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCandidatosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCandidatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBotoesVoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVotar, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNumCC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotoesVoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDataNasc.getAccessibleContext().setAccessibleName("txtDataNasc");
        panelBotoesVoto.getAccessibleContext().setAccessibleName("Votação");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        // TODO add your handling code here:
        index = listCandidatos.getSelectedIndex();
        v = new Voto(cand);
        menu.votos.add(v);
        int soma = menu.resultados.get(index) + 1;
        menu.resultados.set(index, soma);
        menu.votantes.add(e);
        menu.eleitores.remove(indiceElect);
        constroiBloco();
        this.dispose();
        new autenticacao(menu, true).setVisible(true);
    }//GEN-LAST:event_btnVotarActionPerformed

    private void listCandidatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCandidatosValueChanged
        // TODO add your handling code here:
        index = listCandidatos.getSelectedIndex();
        int tamanho = dList.size();
        if (index >= 0) {
            Candidato c = (Candidato) listCandidatos.getSelectedValues()[0];
            menu.candidatos.get(index);
            cand = menu.candidatos.get(index);
            txtNome.setText(e.getNome());
            labelCandidato.setText(c.getNome());
            ImageIcon icon = new ImageIcon(c.getImagem());
            Image imagem = icon.getImage().getScaledInstance(imgCandidato.getWidth(), imgCandidato.getHeight(), Image.SCALE_SMOOTH);
            panelCandidato.setBackground(Color.white);
            imgCandidato.setBackground(Color.white);
            imgCandidato.setIcon(new ImageIcon(imagem));
        }
    }//GEN-LAST:event_listCandidatosValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVotar;
    private javax.swing.JLabel imgCandidato;
    private javax.swing.JLabel imgEleitor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCandidato;
    private javax.swing.JList<String> listCandidatos;
    private javax.swing.JPanel panelBotoesVoto;
    private javax.swing.JPanel panelCandidato;
    private javax.swing.JLabel txtDataNasc;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNumCC;
    // End of variables declaration//GEN-END:variables

    public void constroiBloco() {
        int tamanho = menu.blockchain.getChain().size();
        int ini = tamanho * 8;
        int fin = (tamanho + 1) * 8 - 1;
        ArrayList<Voto> elems = new ArrayList<>();
        if (menu.votos.size() % 8 == 0 && menu.votos.size() >= 8) {
            for (int j = ini; j < fin; j++) {
                elems.add(menu.votos.get(j));
            }
            tree = new MerkleTreeString(elems);
            menu.blockchain.add(tree.getRoot(), 5);
            System.out.println(tree.getHashTree());
        }
    }
}
