/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicao.gui;

import eleicao.core.Candidato;
import eleicao.utils.Recursos;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author menuInicial
 */
public class menuCandidato extends javax.swing.JDialog {

    menuInicial menu;
    DefaultListModel dList;
    int index;
    int tamanho;
    File f;

    /**
     * Creates new form menuCandidatos
     *
     * @param parent
     * @param menu
     * @param model
     */
    public menuCandidato(JDialog parent, menuInicial menu, boolean model) {
        super(parent, model);
        this.menu = menu;
        initComponents();
        if (menu.candidatos != null) {
            dList = Recursos.listaCandidatos(menu.candidatos);
            tamanho = dList.getSize();
            if(tamanho == 0){
                index = -1;
            }else{
                index = 0;
            }
            listCandidatos.setModel(dList);
            listCandidatos.setSelectedIndex(0);
            for (int i = 0; i <= menu.candidatos.size() - 1; i++) {
                menu.resultados.add(i, 0);
            }
        }
        panelCandidato.setVisible(dList.size() > 0);
        btnEliminaCandidato.setEnabled(dList.size() > 0);
        panelButoes.setVisible(dList.size() > 0);
        lblRegisto.setEnabled(dList.size() > 0);
        btnEditarCandidato.setEnabled(dList.size() > 0);
        btnPrimeiro.setEnabled(index > 1);
        btnAnterior.setEnabled(index > 1);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCandidatos = new javax.swing.JList<>();
        btnSair = new javax.swing.JButton();
        panelCandidato = new javax.swing.JPanel();
        panelFoto = new javax.swing.JPanel();
        labelFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnOpen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panelButoes = new javax.swing.JPanel();
        btnPrimeiro = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnNovoCandidato = new javax.swing.JButton();
        btnEliminaCandidato = new javax.swing.JButton();
        btnEditarCandidato = new javax.swing.JButton();
        lblRegisto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Candidato");

        listCandidatos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCandidatos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCandidatosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCandidatos);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        labelFoto.setForeground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setText("    ID");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtID.setEditable(false);

        jLabel6.setText("      Sigla");

        txtSigla.setEditable(false);

        jLabel7.setText("                    Nome ");

        txtNome.setEditable(false);

        javax.swing.GroupLayout panelCandidatoLayout = new javax.swing.GroupLayout(panelCandidato);
        panelCandidato.setLayout(panelCandidatoLayout);
        panelCandidatoLayout.setHorizontalGroup(
            panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCandidatoLayout.createSequentialGroup()
                .addGap(0, 94, Short.MAX_VALUE)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(panelCandidatoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCandidatoLayout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCandidatoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCandidatoLayout.setVerticalGroup(
            panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCandidatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/abrir.png"))); // NOI18N
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel3.setText("   Guardar");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/guardarFicheiro.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel8.setText(" Abrir");

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Primeiro.png"))); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Ultimo.png"))); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Anterior.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Proximo.png"))); // NOI18N
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButoesLayout = new javax.swing.GroupLayout(panelButoes);
        panelButoes.setLayout(panelButoesLayout);
        panelButoesLayout.setHorizontalGroup(
            panelButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrimeiro)
                .addGap(18, 18, 18)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnUltimo)
                .addGap(18, 18, 18))
        );
        panelButoesLayout.setVerticalGroup(
            panelButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovoCandidato.setText("Adicionar Candidato");
        btnNovoCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCandidatoActionPerformed(evt);
            }
        });

        btnEliminaCandidato.setText("Eliminar Candidato");
        btnEliminaCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaCandidatoActionPerformed(evt);
            }
        });

        btnEditarCandidato.setText("Editar Candidato");
        btnEditarCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCandidatoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarCandidato)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminaCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblRegisto.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(panelButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lblRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(31, 31, 31)
                                .addComponent(btnOpen)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelCandidato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblRegisto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelButoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminaCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaCandidatoActionPerformed
        tamanho = dList.size();
        index = listCandidatos.getSelectedIndex();
        dList = Recursos.listaCandidatos(menu.candidatos);
        if (tamanho >= 0) {
            dList.remove(index);
            menu.candidatos.remove(index);
            int indice = 0;
            if (index - 1 > 0) {
                index -= 1;
                indice = index;
            } else {
                index = 0;
                indice = index;
            }
            dList.clear();
            listCandidatos.setModel(dList);
            dList = Recursos.listaCandidatos(menu.candidatos);
            listCandidatos.setModel(dList);
            listCandidatos.setSelectedIndex(indice);
        }
        btnEliminaCandidato.setEnabled(dList.size() > 0);
        panelCandidato.setVisible(dList.size() > 0);
        panelButoes.setVisible(dList.size() > 0);
        btnPrimeiro.setEnabled(index > 1);
        btnAnterior.setEnabled(index > 1);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);
    }//GEN-LAST:event_btnEliminaCandidatoActionPerformed

    private void btnNovoCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCandidatoActionPerformed
        this.dispose();
        new adicionaCandidato(this, f, menu, true).setVisible(true);
    }//GEN-LAST:event_btnNovoCandidatoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
        new configEleicaoMenu(menu, true).setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void listCandidatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCandidatosValueChanged
        // TODO add your handling code here:
        index = listCandidatos.getSelectedIndex();
        tamanho = dList.size();
        lblRegisto.setText("Registo " + (index + 1) + "/" + tamanho);
        if (index >= 0) {
            mostraPanelCandidato();
            Candidato c = (Candidato) listCandidatos.getSelectedValues()[0];
            menu.candidatos.get(index);
            txtNome.setText(c.getNome());
            txtID.setText(String.valueOf(c.getIdCandidato()));
            txtSigla.setText(c.getSigla());
            ImageIcon icon = new ImageIcon(c.getImagem());
            Image imagem = icon.getImage().getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_SMOOTH);
            panelFoto.setBackground(Color.white);
            labelFoto.setBackground(Color.white);
            labelFoto.setIcon(new ImageIcon(imagem));
        }
        btnPrimeiro.setEnabled(index > 1);
        btnAnterior.setEnabled(index > 1);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);
    }//GEN-LAST:event_listCandidatosValueChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("../Eleicao_Blockchain_Teste/candidatos");
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {

                f = fc.getSelectedFile();
                if (!f.getName().endsWith(".cand")) {
                    f = new File(f.getAbsolutePath() + ".cand");
                }
                Recursos.writeObject(menu.candidatos, f.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("../Eleicao_Blockchain_Teste/candidatos");
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                f = fc.getSelectedFile();
                menu.candidatos = (ArrayList<Candidato>) Recursos.readObject(f.getAbsolutePath());
                dList = Recursos.listaCandidatos(menu.candidatos);
                tamanho = dList.getSize();
                listCandidatos.setModel(dList);
                index = 0;
                listCandidatos.setSelectedIndex(index);
                panelCandidato.setVisible(dList.size() > 0);
                btnEliminaCandidato.setEnabled(dList.size() > 0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        for (int i = 0; i <= menu.candidatos.size() - 1; i++) {
                menu.resultados.add(i, 0);
        }
        lblRegisto.setText("Registo " + (index + 1) + "/" + dList.size());
        btnEliminaCandidato.setEnabled(dList.size() > 0);
        panelCandidato.setVisible(dList.size() > 0);
        panelButoes.setVisible(dList.size() > 0);
        btnPrimeiro.setEnabled(index > 1);
        btnAnterior.setEnabled(index > 1);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnEditarCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCandidatoActionPerformed
        // TODO add your handling code here:
        index = listCandidatos.getSelectedIndex();
        Candidato cand = menu.candidatos.get(index);
        this.dispose();
        new editaCandidato(this, cand, index, f, menu, true).setVisible(true);
    }//GEN-LAST:event_btnEditarCandidatoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        // TODO add your handling code here:
        index = 0;
        listCandidatos.setSelectedIndex(index);
        lblRegisto.setText("Registo " + (index + 1) + "/" + dList.size());
        btnPrimeiro.setEnabled(index > 0);
        btnAnterior.setEnabled(index > 0);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        tamanho = dList.size();
        index -= 1;
        if (tamanho > index) {
            listCandidatos.setSelectedIndex(index);
            lblRegisto.setText("Registo " + (index + 1) + "/" + tamanho);
            btnPrimeiro.setEnabled(index > 0);
            btnAnterior.setEnabled(index > 0);
            btnAvancar.setEnabled(index < tamanho - 1);
            btnUltimo.setEnabled(index < tamanho - 1);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        // TODO add your handling code here:
        tamanho = dList.size();
        index += 1;
        if (tamanho > index) {
            listCandidatos.setSelectedIndex(index);
            lblRegisto.setText("Registo " + (index + 1) + "/" + tamanho);
            btnPrimeiro.setEnabled(index > 0);
            btnAnterior.setEnabled(index > 0);
            btnAvancar.setEnabled(index < tamanho - 1);
            btnUltimo.setEnabled(index < tamanho - 1);
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        // TODO add your handling code here:
        index = dList.size() - 1;
        listCandidatos.setSelectedIndex(index);
        lblRegisto.setText("Registo " + dList.size() + "/" + dList.size());
        btnPrimeiro.setEnabled(index > 0);
        btnAnterior.setEnabled(index > 0);
        btnAvancar.setEnabled(index < dList.getSize() - 1);
        btnUltimo.setEnabled(index < dList.getSize() - 1);
    }//GEN-LAST:event_btnUltimoActionPerformed
    public void mostraPanelCandidato() {
        panelFoto.setVisible(true);
        labelFoto.setVisible(true);
        txtNome.setVisible(true);
        txtSigla.setVisible(true);
        txtID.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnEditarCandidato;
    private javax.swing.JButton btnEliminaCandidato;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNovoCandidato;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel lblRegisto;
    private javax.swing.JList<String> listCandidatos;
    private javax.swing.JPanel panelButoes;
    private javax.swing.JPanel panelCandidato;
    private javax.swing.JPanel panelFoto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
