/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eleicao.gui;

import eleicao.blockchain.Block;
import eleicao.blockchain.MerkleTreeString;
import eleicao.core.Eleicao;
import eleicao.core.Eleitor;
import eleicao.utils.Recursos;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author menuInicial
 */
public class resultados extends javax.swing.JDialog {

    menuInicial menu;
    DefaultListModel dListEleitores;
    DefaultListModel dListVotos;
    int tamanho;
    int index;
    int votosTotais;
    String txtArea = "";
    File f;
    ArrayList resultados;
    int percentagem;

    /**
     * Creates new form Resultados
     * @param parent
     * @param model
     */
    public resultados(menuInicial parent, boolean model) {
        super(parent, model);
        this.menu = parent;
        initComponents();
        if (menu.votantes != null) {
            dListEleitores = Recursos.listaEleitores(menu.votantes);
            tamanho = dListEleitores.getSize();
            listEleitores.setModel(dListEleitores);
        }
        if (menu.votos != null) {
            dListVotos = Recursos.listaVotos(menu.votos);
            votosTotais = dListVotos.getSize();
            listaVotos.setModel(dListVotos);
            listaVotos.setSelectedIndex(0);
            txtBlockchain.setText(menu.blockchain.toString());
        }
        votosTotais = menu.votos.size();
        for (int i = 0; i <= menu.candidatos.size() - 1; i++) {
            txtArea += menu.candidatos.get(i).toString()
                    + "\t" + menu.resultados.get(i) + " votos \n";
        }
        jTextArea1.setText(txtArea);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelResultados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelVotantes = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEleitores = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        panelVotos = new javax.swing.JPanel();
        panelListaVotos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVotos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        panelBlockchain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBlockchain = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultados");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/guardarFicheiro.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/abrir.png"))); // NOI18N
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        jLabel5.setText("     Guardar");

        jLabel12.setText("    Abrir");

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelResultadosLayout.createSequentialGroup()
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResultadosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12))
                            .addComponent(btnOpen))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Resultados", panelResultados);

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eleicao/images/Pesquisa.png"))); // NOI18N
        btnPesquisa.setText("Pesquisa");
        btnPesquisa.setHideActionText(true);
        btnPesquisa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnPesquisa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        listEleitores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEleitores.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listEleitoresValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listEleitores);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Lista Eleitoral");

        javax.swing.GroupLayout panelVotantesLayout = new javax.swing.GroupLayout(panelVotantes);
        panelVotantes.setLayout(panelVotantesLayout);
        panelVotantesLayout.setHorizontalGroup(
            panelVotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVotantesLayout.createSequentialGroup()
                        .addComponent(btnPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelVotantesLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVotantesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        panelVotantesLayout.setVerticalGroup(
            panelVotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVotantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Votantes", panelVotantes);

        jScrollPane2.setViewportView(listaVotos);

        javax.swing.GroupLayout panelListaVotosLayout = new javax.swing.GroupLayout(panelListaVotos);
        panelListaVotos.setLayout(panelListaVotosLayout);
        panelListaVotosLayout.setHorizontalGroup(
            panelListaVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
        );
        panelListaVotosLayout.setVerticalGroup(
            panelListaVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lista de Candidatos");

        javax.swing.GroupLayout panelVotosLayout = new javax.swing.GroupLayout(panelVotos);
        panelVotos.setLayout(panelVotosLayout);
        panelVotosLayout.setHorizontalGroup(
            panelVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelListaVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelVotosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelVotosLayout.setVerticalGroup(
            panelVotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVotosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelListaVotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Votos", panelVotos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Blockchain");

        txtBlockchain.setColumns(20);
        txtBlockchain.setRows(5);
        jScrollPane4.setViewportView(txtBlockchain);

        javax.swing.GroupLayout panelBlockchainLayout = new javax.swing.GroupLayout(panelBlockchain);
        panelBlockchain.setLayout(panelBlockchainLayout);
        panelBlockchainLayout.setHorizontalGroup(
            panelBlockchainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlockchainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBlockchainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(panelBlockchainLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 351, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBlockchainLayout.setVerticalGroup(
            panelBlockchainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlockchainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BlockChain", panelBlockchain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEleitoresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEleitoresValueChanged
        // TODO add your handling code here:
        tamanho = dListEleitores.size();
        Eleitor e = (Eleitor) listEleitores.getSelectedValues()[0];
        index = listEleitores.getSelectedIndex();
        menu.eleitores.get(index);
    }//GEN-LAST:event_listEleitoresValueChanged

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i <= menu.eleitores.size() - 1; i++) {
            if (txtPesquisa.getText().trim().equals(menu.eleitores.get(i).getCC())) {
                listEleitores.setSelectedIndex(i);
                break;
            }
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("../Eleicao_Blockchain_Teste/eleicao");
        if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                f = fc.getSelectedFile();
                if (!f.getName().endsWith(".eleicao")) {
                    f = new File(f.getAbsolutePath() + ".eleicao");
                }
                menu.eleicao = new Eleicao(menu.votantes, menu.candidatos, menu.votos, menu.resultados);
                Recursos.writeObject(menu.eleicao, f.getAbsolutePath());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser("../Eleicao_Blockchain_Teste/eleicao");
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            try {
                f = fc.getSelectedFile();
                menu.eleicao = (Eleicao) Recursos.readObject(f.getAbsolutePath());
                dListEleitores = Recursos.listaEleitores(menu.eleicao.getEleitores());
                listEleitores.setModel(dListEleitores);
                dListVotos = Recursos.listaVotos(menu.eleicao.getVotos());
                listaVotos.setModel(dListVotos);
                for (int i = 0; i <= menu.eleicao.getCandidatos().size() - 1; i++) {
                    txtArea += menu.eleicao.getCandidatos().get(i).toString()
                            + "\t" + menu.eleicao.getResultados().get(i) + " votos \n";
                }
                jTextArea1.setText(txtArea);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> listEleitores;
    private javax.swing.JList<String> listaVotos;
    private javax.swing.JPanel panelBlockchain;
    private javax.swing.JPanel panelListaVotos;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JPanel panelVotantes;
    private javax.swing.JPanel panelVotos;
    private javax.swing.JTextArea txtBlockchain;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

}



